spring:
 main:
  show-banner: true
 logging:
  path: ./logs
  file: doshou-web.log
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/doshou_db?useUnicode=true&characterEncoding=utf-8
  username: root
  password: adminadmin
  max-active: 100
  max-idle: 10
  min-idle: 10
  initial-size: 10
  validation-query: select 1
  test-on-borrow: false
  test-on-return: false
  test-while-idle: true
  time-between-eviction-runs-millis: 60000
  min-evictable-idle-time-millis: 300000
  max-wait: 60000
 thymeleaf:
  mode: HTML5
  encoding: UTF-8
  content-type: text/html
  cache: false